### PR TITLE
Footer, Nav and JS

### PR DESCRIPTION
**Pull request by tuesdayshaw**
- [x] increased font size for footer
- [x] added hamburger to nav when user is logged out and tablet/mobile screen
- [x] labeled bootstrap popover javascript functionality that was implemented earlier

### CODE REVIEW

**Review by roxanavp87 — APPROVED** [review]

**Comment by roxanavp87** [comment]
looks good!

**Comment by roxanavp87** [comment]
For mobile version, increase the font-size in the navbar.

**Comment by roxanavp87** [comment]
footer and hamburger looks nice

**Comment by roxanavp87** [comment]
font-size to fill in the form is small, maybe increase it a little

screen shot 2017-07-06 at 11 39 42 pm

**Comment by tuesdayshaw** [comment]
All done :)

**Pull request merged**
